policies_plan_abbr_name:
  values:
    - "生财宝"
    - "智能星"
    - "金利多"
    - "平安永福"
    - "平安康泰"
    - "盛世金越"
    - "e生保"
    - "安康"
    - "平安宝贝"
    - "i康保"
    - "i药保"
    - "海外"
    - "抗癌"
    - "尊享"
    - "尊优"
    - "舒享"
    - "其他"
